const SETTINGS_KEY="numberPattern.settings.v2",HISTORY_KEY="numberPattern.history.v2";
const DEFAULTS={nBack:2,trialCount:24,infinite:false,spoken:false,speechRate:.85,trialDelayMs:0};
const RULES=[
{id:"add2",label:"add 2",make:s=>[s,s+2,s+4,s+6]},{id:"add3",label:"add 3",make:s=>[s,s+3,s+6,s+9]},{id:"add5",label:"add 5",make:s=>[s,s+5,s+10,s+15]},
{id:"subtract2",label:"subtract 2",make:s=>[s,s-2,s-4,s-6]},{id:"subtract3",label:"subtract 3",make:s=>[s,s-3,s-6,s-9]},
{id:"times2",label:"multiply by 2",make:s=>[s,s*2,s*4,s*8]},{id:"times3",label:"multiply by 3",make:s=>[s,s*3,s*9,s*27]},
{id:"divide2",label:"divide by 2",starts:[16,24,32,40,48,64],make:s=>[s,s/2,s/4,s/8]}];
const $=s=>document.querySelector(s),views=["home","play","game","summary","progress"];
const els={home:$("#home-button"),begin:$("#begin-button"),start:$("#start-game"),n:$("#n-back"),count:$("#trial-count"),custom:$("#custom-trial-count"),spoken:$("#spoken-premises"),rate:$("#speech-rate"),delay:$("#trial-delay"),label:$("#trial-label"),bar:$("#progress-bar"),badge:$("#n-badge"),score:$("#score-badge"),series:$("#series"),answers:$("#answer-options"),memory:$("#memory-card"),question:$("#memory-question"),warmup:$("#warmup-note"),feedback:$("#feedback"),submit:$("#submit-answer"),next:$("#next-trial"),end:$("#end-game"),summaryHeading:$("#summary-heading"),total:$("#total-score"),summaryGrid:$("#summary-grid"),summaryNote:$("#summary-note"),again:$("#train-again"),history:$("#history-list")};
const state={settings:loadObject(SETTINGS_KEY,DEFAULTS),history:loadArray(HISTORY_KEY),trials:[],index:0,results:[],answer:null,match:null,locked:false,started:0,timer:0,active:false};
init();
function loadObject(k,f){try{const v=JSON.parse(localStorage.getItem(k)||"null");return v&&typeof v==="object"&&!Array.isArray(v)?{...f,...v}:{...f}}catch{return{...f}}}
function loadArray(k){try{const v=JSON.parse(localStorage.getItem(k)||"[]");return Array.isArray(v)?v:[]}catch{return[]}}
function save(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
function init(){setCountUi();els.n.value=String(state.settings.nBack);els.spoken.checked=!!state.settings.spoken;els.rate.value=String(state.settings.speechRate);els.delay.value=String(state.settings.trialDelayMs);document.addEventListener("click",click);els.home.onclick=()=>show("home");els.begin.onclick=()=>show("play");els.count.onchange=syncCustom;els.start.onpointerdown=primeSpeech;els.start.onclick=start;els.submit.onclick=submit;els.next.onclick=requestNext;els.end.onclick=end;els.again.onclick=()=>show("play");show("home")}
function show(name){views.forEach(v=>$("#"+v+"-view").hidden=v!==name);document.querySelectorAll("nav button[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===name));if(name==="progress")renderHistory();if(name!=="game")cancelSpeech();scrollTo({top:0,behavior:"auto"})}
function click(e){const nav=e.target.closest("[data-view]");if(nav){show(nav.dataset.view);return}const a=e.target.closest("button[data-answer]");if(a&&!state.locked){state.answer=Number(a.dataset.answer);selectOnly(els.answers,a);updateSubmit();return}const m=e.target.closest("button[data-match]");if(m&&!state.locked){state.match=m.dataset.match==="true";selectOnly(els.memory.querySelector(".match-options"),m);updateSubmit()}}
function selectOnly(c,s){c.querySelectorAll("button").forEach(b=>b.classList.toggle("selected",b===s))}
function setCountUi(){if(state.settings.infinite){els.count.value="infinite";els.custom.hidden=true;return}const c=state.settings.trialCount||24,p=[...els.count.options].some(o=>o.value===String(c));els.count.value=p?String(c):"custom";els.custom.hidden=p;els.custom.value=p?"":String(c)}
function syncCustom(){const c=els.count.value==="custom";els.custom.hidden=!c;if(c){if(!els.custom.value)els.custom.value=String(state.settings.trialCount||24);els.custom.focus()}}
function readSettings(){const infinite=els.count.value==="infinite";let trialCount=state.settings.trialCount||24;if(!infinite){trialCount=els.count.value==="custom"?Number(els.custom.value):Number(els.count.value);if(!Number.isInteger(trialCount)||trialCount<1)throw Error("Enter a whole number of trials greater than zero.")}return{nBack:Number(els.n.value),trialCount,infinite,spoken:els.spoken.checked,speechRate:Number(els.rate.value),trialDelayMs:Number(els.delay.value)}}
function start(){try{state.settings=readSettings()}catch(e){alert(e.message);return}save(SETTINGS_KEY,state.settings);state.trials=[];state.index=0;state.results=[];state.active=true;ensure(0);show("game");render()}
function ensure(i){while(state.trials.length<=i)state.trials.push(makeTrial(state.trials.length))}
function makeTrial(i){const n=state.settings.nBack,can=i>=n,force=can&&Math.random()<.34;let rule;if(force)rule=RULES.find(r=>r.id===state.trials[i-n].ruleId);else{const forbidden=can?state.trials[i-n].ruleId:state.trials.at(-1)?.ruleId,choices=RULES.filter(r=>r.id!==forbidden);rule=choices[Math.floor(Math.random()*choices.length)]}const start=chooseStart(rule),numbers=rule.make(start),correct=numbers[3];return{ruleId:rule.id,ruleLabel:rule.label,numbers,correct,options:options(correct,numbers),match:can?rule.id===state.trials[i-n].ruleId:null}}
function chooseStart(r){if(r.starts)return r.starts[Math.floor(Math.random()*r.starts.length)];if(r.id.startsWith("subtract"))return 12+Math.floor(Math.random()*19);if(r.id.startsWith("times3"))return 1+Math.floor(Math.random()*3);if(r.id.startsWith("times2"))return 2+Math.floor(Math.random()*6);return 1+Math.floor(Math.random()*18)}
function options(correct,numbers){const v=new Set([correct]),step=Math.max(1,Math.abs(numbers[2]-numbers[1]));for(const x of[correct+step,correct-step,correct+2,correct-2,correct+3,correct-3,numbers[2],numbers[2]+1]){if(Number.isFinite(x)&&x>=0)v.add(x);if(v.size===4)break}while(v.size<4)v.add(correct+v.size*4+1);return[...v].sort(()=>Math.random()-.5)}
function render(){const t=state.trials[state.index];state.answer=null;state.match=null;state.locked=false;state.started=performance.now();els.label.textContent=state.settings.infinite?`Trial ${state.index+1} · Infinite`:`Trial ${state.index+1} / ${state.settings.trialCount}`;els.bar.style.width=state.settings.infinite?"100%":`${(state.index+1)/state.settings.trialCount*100}%`;els.badge.textContent=`${state.settings.nBack}-back`;els.score.textContent=liveScore();els.series.replaceChildren(...t.numbers.slice(0,3).flatMap((x,i)=>{const s=document.createElement("span");s.textContent=String(x);return i?[document.createTextNode(","),s]:[s]}),document.createTextNode(","),Object.assign(document.createElement("span"),{textContent:"?",className:"missing"}));els.answers.replaceChildren(...t.options.map(x=>{const b=document.createElement("button");b.type="button";b.dataset.answer=String(x);b.textContent=String(x);return b}));els.question.textContent=`Does this rule match the rule from ${state.settings.nBack} trial${state.settings.nBack===1?"":"s"} ago?`;const w=t.match===null;els.memory.querySelectorAll("button[data-match]").forEach(b=>{b.disabled=w;b.className=""});els.warmup.textContent=w?`Memory warm-up: comparison begins on trial ${state.settings.nBack+1}.`:"Compare the abstract generating rule, not the values.";els.feedback.hidden=true;els.feedback.replaceChildren();els.submit.hidden=false;els.submit.disabled=true;els.next.hidden=true;els.next.disabled=false;speak(t.numbers)}
function updateSubmit(){const need=state.trials[state.index].match!==null;els.submit.disabled=state.answer===null||(need&&state.match===null)}
function submit(){if(els.submit.disabled||state.locked)return;state.locked=true;cancelSpeech();const t=state.trials[state.index],solution=state.answer===t.correct,match=t.match===null?null:state.match===t.match;state.results.push({solutionCorrect:solution,matchCorrect:match,responseTimeMs:performance.now()-state.started});mark(t);els.feedback.hidden=false;els.feedback.innerHTML=`<strong>${solution&&match!==false?"Correct relational reading.":"Review the generating rule."}</strong><span>The series follows <b>${t.ruleLabel}</b>, so the missing number is <b>${t.correct}</b>${t.match===null?".":`; the n-back response was <b>${t.match?"match":"different"}</b>.`}</span>`;els.score.textContent=liveScore();els.submit.hidden=true;els.next.hidden=false;els.next.textContent=state.settings.infinite?"Next trial":state.index===state.settings.trialCount-1?"Finish session":"Next trial"}
function mark(t){els.answers.querySelectorAll("button").forEach(b=>{b.disabled=true;const v=Number(b.dataset.answer);b.classList.remove("selected");if(v===t.correct)b.classList.add("correct");else if(v===state.answer)b.classList.add("wrong")});els.memory.querySelectorAll("button[data-match]").forEach(b=>{b.disabled=true;if(t.match===null)return;const v=b.dataset.match==="true";b.classList.remove("selected");if(v===t.match)b.classList.add("correct");else if(v===state.match)b.classList.add("wrong")})}
function requestNext(){els.next.disabled=true;const d=state.settings.trialDelayMs;if(d)state.timer=setTimeout(advance,d);else advance()}
function advance(){state.timer=0;els.next.disabled=false;if(!state.settings.infinite&&state.index>=state.settings.trialCount-1){finish();return}state.index++;ensure(state.index);render()}
function end(){if(!state.active||!confirm(state.settings.infinite?"End the infinite session and save completed trials?":"End this session now and save completed trials?"))return;clearTimeout(state.timer);state.results.length?finish():(state.active=false,show("play"))}
function finish(){cancelSpeech();state.active=false;const solution=pct(state.results.map(r=>r.solutionCorrect)),match=pct(state.results.filter(r=>r.matchCorrect!==null).map(r=>r.matchCorrect)),total=Math.round((solution+match)/2),trials=state.results.length,record={date:new Date().toISOString(),nBack:state.settings.nBack,trials,infinite:state.settings.infinite,solution,match,total,spoken:state.settings.spoken,speechRate:state.settings.speechRate,trialDelayMs:state.settings.trialDelayMs};state.history.unshift(record);state.history=state.history.slice(0,100);save(HISTORY_KEY,state.history);els.total.textContent=`${total}%`;els.summaryHeading.textContent=total>=85?"Pattern memory held":total>=70?"Proof of principle established":"Rule discrimination needs reinforcement";els.summaryGrid.innerHTML=`<article><span>Series solutions</span><strong>${solution}%</strong></article><article><span>Pattern n-back</span><strong>${match}%</strong></article>`;els.summaryNote.textContent=`Completed ${trials} trial${trials===1?"":"s"} at ${state.settings.nBack}-back${state.settings.infinite?" in infinite mode":""}.`;show("summary")}
function pct(v){return v.length?Math.round(v.filter(Boolean).length/v.length*100):0}function liveScore(){if(!state.results.length)return"Score —";return`Score ${pct(state.results.flatMap(r=>[r.solutionCorrect,r.matchCorrect].filter(v=>v!==null)))}%`}
function renderHistory(){els.history.innerHTML=state.history.length?state.history.map(r=>`<article class="history-card"><header><div><b>${new Date(r.date).toLocaleString()}</b><p>${r.nBack}-back · ${r.trials} trials${r.infinite?" · infinite mode":""}${r.spoken?" · auditory":""}</p></div><strong>${r.total}%</strong></header><p>Solutions ${r.solution}% · Pattern memory ${r.match}%</p></article>`).join(""):`<article class="history-card"><strong>No completed sessions yet.</strong><p>Finish a session to establish the first baseline.</p></article>`}
function primeSpeech(){if(!els.spoken.checked||!window.speechSynthesis||!window.SpeechSynthesisUtterance)return;try{speechSynthesis.cancel();speechSynthesis.resume();const u=new SpeechSynthesisUtterance(" ");u.volume=0;speechSynthesis.speak(u)}catch{}}
function speak(n){cancelSpeech();if(!state.settings.spoken||!window.speechSynthesis||!window.SpeechSynthesisUtterance)return;const u=new SpeechSynthesisUtterance(`${n[0]}, ${n[1]}, ${n[2]}, what is the fourth number?`);u.lang="en-AU";u.rate=state.settings.speechRate;try{speechSynthesis.speak(u)}catch{}}
function cancelSpeech(){try{window.speechSynthesis?.cancel()}catch{}}window.addEventListener("beforeunload",cancelSpeech);document.addEventListener("visibilitychange",()=>{if(document.hidden)cancelSpeech()});